name: List Files on PR

on:
  pull_request:
    branches:
      - main

jobs:
  list-files:
    if: ${{ vars.MODE == 'on' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the current directory
        run: ls
  show-current-directory:
    if: ${{ vars.MODE == 'off' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: print current director
        run: pwd
