name: List Files on PR

on:
  pull_request:
    branches:
      - main

  pull_request_target:
    types:
      - edited

jobs:
  list-files:
    if: ${{ vars.MODE == 'on' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: List files in the current directory
        run: ls

  show-current-directory:
    if: contains(fromJSON('["${{ vars.TEST_USERS }}"]'), github.event.pull_request.user.login)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo author of the PR
        run: |
          echo "Author of the PR: $PR_AUTHOR"
          echo "Test users: $TEST_USERS"
        env:
          PR_AUTHOR: ${{ github.event.pull_request.user.login }}
          TEST_USERS: ${{ vars.TEST_USERS }}

